services:
  - type: web
    name: flipkart-scraper-api
    runtime: python
    plan: free
    buildCommand: bash render-build.sh
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
